### ISSUE TITLE
A small bug in riptide_search

### ISSUE THREAD

**Issue by astrogqzhang** [KshitijAggarwal/frbpa#3]
In the lines 66, 67 of search.py, i.e.
`ts_arr = np.linspace(np.min(bursts), np.max(bursts), 
                         (np.max(bursts)-np.min(bursts))/ts_bin_width)`
the third parameter may not be an integer.  Actually,  I have encountered this error. 
May be it should be replaced with 
`int((np.max(bursts)-np.min(bursts))/ts_bin_width)`

**Comment by KshitijAggarwal** [comment]
Fixed with 08c6c0d12c6842f1761b9febdb955fa46bcf3794.
